CREATE TABLE pharmacy_system_settings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    pharmacy_id BIGINT,
    notifications_enabled BOOLEAN DEFAULT TRUE,
    inventory_alerts BOOLEAN DEFAULT TRUE,
    expiry_alerts BOOLEAN DEFAULT TRUE,
    system_messages BOOLEAN DEFAULT TRUE,
    theme VARCHAR(255) DEFAULT 'Light',
    default_homepage VARCHAR(255) DEFAULT 'Dashboard',
    FOREIGN KEY (pharmacy_id) REFERENCES pharmacy(id)
);

INSERT INTO pharmacy_system_settings
(pharmacy_id, notifications_enabled, inventory_alerts, expiry_alerts, system_messages, theme, default_homepage)
VALUES
(1, TRUE, TRUE, TRUE, TRUE, 'Light', 'Dashboard'),
(2, TRUE, TRUE, FALSE, TRUE, 'Dark', 'Dashboard'),
(3, TRUE, FALSE, TRUE, TRUE, 'Light', 'Orders'),
(4, FALSE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard'),
(5, TRUE, TRUE, TRUE, FALSE, 'Light', 'Dashboard'),
(6, TRUE, FALSE, FALSE, TRUE, 'Dark', 'Orders'),
(7, TRUE, TRUE, TRUE, TRUE, 'Light', 'Dashboard'),
(8, FALSE, TRUE, TRUE, FALSE, 'Dark', 'Dashboard'),
(9, TRUE, TRUE, TRUE, TRUE, 'Light', 'Inventory'),
(10, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard'),
(11, TRUE, TRUE, FALSE, TRUE, 'Light', 'Dashboard'),
(12, TRUE, FALSE, TRUE, TRUE, 'Dark', 'Orders'),
(13, TRUE, TRUE, TRUE, TRUE, 'Light', 'Dashboard'),
(14, TRUE, TRUE, TRUE, FALSE, 'Dark', 'Dashboard'),
(15, TRUE, TRUE, TRUE, TRUE, 'Light', 'Inventory'),
(16, TRUE, FALSE, TRUE, TRUE, 'Dark', 'Dashboard'),
(17, TRUE, TRUE, FALSE, TRUE, 'Light', 'Dashboard'),
(18, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Orders'),
(19, TRUE, TRUE, FALSE, TRUE, 'Light', 'Dashboard'),
(20, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard'),
(21, TRUE, FALSE, TRUE, TRUE, 'Light', 'Dashboard'),
(22, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard'),
(23, TRUE, TRUE, TRUE, TRUE, 'Light', 'Orders'),
(24, TRUE, FALSE, TRUE, TRUE, 'Dark', 'Dashboard'),
(25, TRUE, TRUE, TRUE, FALSE, 'Light', 'Dashboard'),
(26, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Inventory'),
(27, TRUE, FALSE, TRUE, TRUE, 'Light', 'Dashboard'),
(28, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard'),
(29, TRUE, TRUE, FALSE, TRUE, 'Light', 'Dashboard'),
(30, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Orders'),
(31, TRUE, TRUE, FALSE, TRUE, 'Light', 'Dashboard'),
(32, TRUE, FALSE, TRUE, TRUE, 'Dark', 'Dashboard'),
(33, TRUE, TRUE, TRUE, TRUE, 'Light', 'Inventory'),
(34, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard'),
(35, TRUE, FALSE, TRUE, TRUE, 'Light', 'Dashboard'),
(36, TRUE, TRUE, TRUE, FALSE, 'Dark', 'Dashboard'),
(37, TRUE, TRUE, TRUE, TRUE, 'Light', 'Dashboard'),
(38, FALSE, TRUE, TRUE, TRUE, 'Dark', 'Orders'),
(39, TRUE, FALSE, TRUE, TRUE, 'Light', 'Dashboard'),
(40, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard'),
(41, TRUE, TRUE, TRUE, TRUE, 'Light', 'Dashboard'),
(42, FALSE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard'),
(43, TRUE, FALSE, TRUE, TRUE, 'Light', 'Inventory'),
(44, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard'),
(45, TRUE, TRUE, TRUE, TRUE, 'Light', 'Dashboard'),
(46, FALSE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard'),
(47, TRUE, FALSE, TRUE, TRUE, 'Light', 'Dashboard'),
(48, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Orders'),
(49, TRUE, TRUE, TRUE, TRUE, 'Light', 'Dashboard'),
(50, TRUE, TRUE, TRUE, TRUE, 'Dark', 'Dashboard');