CREATE TABLE pharmacy_reports_inquiries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    pharmacy_id BIGINT NOT NULL,
    type ENUM('PHARMACY', 'MEDICINE', 'SYSTEM', 'OTHER'),
    issue_category ENUM('TECHNICAL', 'BUSINESS', 'ACCOUNT', 'OTHER'),
    priority ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'),
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    attachment VARCHAR(255),
    status ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'REJECTED') DEFAULT 'PENDING',
    created_at DATETIME NOT NULL,
    status_changed_at DATETIME,
    FOREIGN KEY (pharmacy_id) REFERENCES pharmacy(id)
);

INSERT INTO pharmacy_reports_inquiries
(pharmacy_id, type, issue_category, priority, title, description, attachment, status, created_at, status_changed_at)
VALUES
(1, 'SYSTEM', 'TECHNICAL', 'HIGH', 'Inventory system glitch', 'Unable to update stock quantities for certain medicines.', 'attachments/report1.pdf', 'PENDING', '2026-01-01 09:00:00', NULL),
(2, 'MEDICINE', 'TECHNICAL', 'MEDIUM', 'Medicine info mismatch', 'Price listed incorrectly in system for medicine X.', 'attachments/report2.pdf', 'PENDING', '2026-01-02 09:30:00', NULL),
(3, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'System downtime', 'Website portal was down for 2 hours.', 'attachments/report3.pdf', 'PENDING', '2026-01-03 10:00:00', NULL),
(4, 'PHARMACY', 'BUSINESS', 'HIGH', 'Payment gateway issue', 'Unable to receive online payments for orders.', 'attachments/report4.pdf', 'PENDING', '2026-01-04 11:00:00', NULL),
(5, 'OTHER', 'OTHER', 'LOW', 'General inquiry', 'Requesting clarification about pharmacy license renewal.', 'attachments/report5.pdf', 'PENDING', '2026-01-05 09:45:00', NULL),
(6, 'SYSTEM', 'TECHNICAL', 'MEDIUM', 'Medicine stock alert error', 'Notifications for low stock not appearing.', 'attachments/report6.pdf', 'PENDING', '2026-01-06 10:20:00', NULL),
(7, 'SYSTEM', 'TECHNICAL', 'HIGH', 'Login failures', 'Staff unable to login to the system intermittently.', 'attachments/report7.pdf', 'PENDING', '2026-01-07 11:15:00', NULL),
(8, 'PHARMACY', 'ACCOUNT', 'MEDIUM', 'Invoice mismatch', 'Invoices generated do not match payment records.', 'attachments/report8.pdf', 'PENDING', '2026-01-08 09:50:00', NULL),
(9, 'MEDICINE', 'TECHNICAL', 'HIGH', 'Medicine expiry dates incorrect', 'Some medicines show expired dates incorrectly.', 'attachments/report9.pdf', 'PENDING', '2026-01-09 10:10:00', NULL),
(10, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'Server crash', 'System server crashed during peak hours.', 'attachments/report10.pdf', 'PENDING', '2026-01-10 11:00:00', NULL),
(11, 'PHARMACY', 'BUSINESS', 'HIGH', 'Billing error', 'Discounts not applied correctly for customers.', 'attachments/report11.pdf', 'PENDING', '2026-01-11 09:00:00', NULL),
(12, 'SYSTEM', 'TECHNICAL', 'MEDIUM', 'Stock reporting issue', 'Monthly reports show incorrect quantities.', 'attachments/report12.pdf', 'PENDING', '2026-01-12 09:30:00', NULL),
(13, 'SYSTEM', 'TECHNICAL', 'HIGH', 'Slow system response', 'System response time exceeds 10 seconds for queries.', 'attachments/report13.pdf', 'PENDING', '2026-01-13 10:00:00', NULL),
(14, 'PHARMACY', 'ACCOUNT', 'LOW', 'Staff account issue', 'New staff accounts cannot be created.', 'attachments/report14.pdf', 'PENDING', '2026-01-14 11:00:00', NULL),
(15, 'OTHER', 'OTHER', 'MEDIUM', 'License document query', 'Cannot upload license document correctly.', 'attachments/report15.pdf', 'PENDING', '2026-01-15 09:45:00', NULL),
(16, 'SYSTEM', 'TECHNICAL', 'HIGH', 'Medicine stock sync error', 'Stock levels not syncing between branches.', 'attachments/report16.pdf', 'PENDING', '2026-01-16 10:20:00', NULL),
(17, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'Portal inaccessible', 'Customers cannot access online ordering portal.', 'attachments/report17.pdf', 'PENDING', '2026-01-17 11:15:00', NULL),
(18, 'MEDICINE', 'TECHNICAL', 'MEDIUM', 'Pricing issue', 'Incorrect price displayed for multiple items.', 'attachments/report18.pdf', 'PENDING', '2026-01-18 09:50:00', NULL),
(19, 'MEDICINE', 'TECHNICAL', 'HIGH', 'Expired stock alert failure', 'Expired stock alert notifications not sent.', 'attachments/report19.pdf', 'PENDING', '2026-01-19 10:10:00', NULL),
(20, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'Database error', 'Database connection lost intermittently.', 'attachments/report20.pdf', 'PENDING', '2026-01-20 11:00:00', NULL),
(21, 'PHARMACY', 'BUSINESS', 'HIGH', 'Customer order issue', 'Orders not reflecting in backend.', 'attachments/report21.pdf', 'PENDING', '2026-01-21 09:00:00', NULL),
(22, 'MEDICINE', 'TECHNICAL', 'MEDIUM', 'Medicine labeling issue', 'Label information not appearing correctly.', 'attachments/report22.pdf', 'PENDING', '2026-01-22 09:30:00', NULL),
(23, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'Server overload', 'System overloaded during high traffic.', 'attachments/report23.pdf', 'PENDING', '2026-01-23 10:00:00', NULL),
(24, 'PHARMACY', 'ACCOUNT', 'LOW', 'Invoice formatting issue', 'Invoice PDF formatting not correct.', 'attachments/report24.pdf', 'PENDING', '2026-01-24 11:00:00', NULL),
(25, 'OTHER', 'OTHER', 'MEDIUM', 'General question', 'Clarification on pharmacy regulations.', 'attachments/report25.pdf', 'PENDING', '2026-01-25 09:45:00', NULL),
(26, 'SYSTEM', 'TECHNICAL', 'HIGH', 'Stock count mismatch', 'Mismatch in inventory count between branches.', 'attachments/report26.pdf', 'PENDING', '2026-01-26 10:20:00', NULL),
(27, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'Website downtime', 'Website went down for maintenance unexpectedly.', 'attachments/report27.pdf', 'PENDING', '2026-01-27 11:15:00', NULL),
(28, 'PHARMACY', 'ACCOUNT', 'MEDIUM', 'Staff login problem', 'Staff cannot login with correct credentials.', 'attachments/report28.pdf', 'PENDING', '2026-01-28 09:50:00', NULL),
(29, 'MEDICINE', 'TECHNICAL', 'HIGH', 'Medicine batch mismatch', 'Incorrect batch information recorded.', 'attachments/report29.pdf', 'PENDING', '2026-01-29 10:10:00', NULL),
(30, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'API failure', 'System APIs not responding.', 'attachments/report30.pdf', 'PENDING', '2026-01-30 11:00:00', NULL),
(31, 'PHARMACY', 'BUSINESS', 'HIGH', 'Billing system lag', 'System delays during invoice generation.', 'attachments/report31.pdf', 'PENDING', '2026-01-31 09:00:00', NULL),
(32, 'SYSTEM', 'TECHNICAL', 'MEDIUM', 'Medicine update issue', 'Cannot update medicine details in system.', 'attachments/report32.pdf', 'PENDING', '2026-02-01 09:30:00', NULL),
(33, 'SYSTEM', 'TECHNICAL', 'HIGH', 'Slow checkout', 'Online checkout slow for customers.', 'attachments/report33.pdf', 'PENDING', '2026-02-02 10:00:00', NULL),
(34, 'PHARMACY', 'ACCOUNT', 'LOW', 'Account registration issue', 'New accounts not reflecting.', 'attachments/report34.pdf', 'PENDING', '2026-02-03 11:00:00', NULL),
(35, 'OTHER', 'OTHER', 'MEDIUM', 'Documentation inquiry', 'Requesting document clarification.', 'attachments/report35.pdf', 'PENDING', '2026-02-04 09:45:00', NULL),
(36, 'SYSTEM', 'TECHNICAL', 'HIGH', 'Stock report error', 'Weekly stock report incorrect.', 'attachments/report36.pdf', 'PENDING', '2026-02-05 10:20:00', NULL),
(37, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'Payment gateway crash', 'Payment API not working.', 'attachments/report37.pdf', 'PENDING', '2026-02-06 11:15:00', NULL),
(38, 'PHARMACY', 'ACCOUNT', 'MEDIUM', 'Invoice mismatch', 'Invoices not reflecting proper amounts.', 'attachments/report38.pdf', 'PENDING', '2026-02-07 09:50:00', NULL),
(39, 'MEDICINE', 'TECHNICAL', 'HIGH', 'Expired medicine notification failed', 'Alerts for expired medicine not sent.', 'attachments/report39.pdf', 'PENDING', '2026-02-08 10:10:00', NULL),
(40, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'System crash', 'Backend crashed during high usage.', 'attachments/report40.pdf', 'PENDING', '2026-02-09 11:00:00', NULL),
(41, 'PHARMACY', 'ACCOUNT', 'HIGH', 'Staff management error', 'Cannot assign roles to staff.', 'attachments/report41.pdf', 'PENDING', '2026-02-10 09:00:00', NULL),
(42, 'MEDICINE', 'TECHNICAL', 'MEDIUM', 'Medicine description error', 'Incorrect description showing on portal.', 'attachments/report42.pdf', 'PENDING', '2026-02-11 09:30:00', NULL),
(43, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'Server maintenance failed', 'Automatic maintenance failed overnight.', 'attachments/report43.pdf', 'PENDING', '2026-02-12 10:00:00', NULL),
(44, 'PHARMACY', 'ACCOUNT', 'LOW', 'Invoice display issue', 'PDF invoices not displaying logo.', 'attachments/report44.pdf', 'PENDING', '2026-02-13 11:00:00', NULL),
(45, 'OTHER', 'OTHER', 'MEDIUM', 'License question', 'Clarification about license renewal date.', 'attachments/report45.pdf', 'PENDING', '2026-02-14 09:45:00', NULL),
(46, 'SYSTEM', 'TECHNICAL', 'HIGH', 'Stock count discrepancy', 'Inventory count differs from system count.', 'attachments/report46.pdf', 'PENDING', '2026-02-15 10:20:00', NULL),
(47, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'Portal outage', 'Customer portal unavailable.', 'attachments/report47.pdf', 'PENDING', '2026-02-16 11:15:00', NULL),
(48, 'PHARMACY', 'ACCOUNT', 'MEDIUM', 'Customer order missing', 'Orders not showing in dashboard.', 'attachments/report48.pdf', 'PENDING', '2026-02-17 09:50:00', NULL),
(49, 'MEDICINE', 'TECHNICAL', 'HIGH', 'Batch info error', 'Incorrect batch number recorded.', 'attachments/report49.pdf', 'PENDING', '2026-02-18 10:10:00', NULL),
(50, 'SYSTEM', 'TECHNICAL', 'CRITICAL', 'System unresponsive', 'Backend unresponsive intermittently.', 'attachments/report50.pdf', 'PENDING', '2026-02-19 11:00:00', NULL);
